### ISSUE TITLE
type 'Future<dynamic>' is not a subtype of type 'FutureOr<List<dynamic>>' in type cast

### ISSUE THREAD

**Issue by selvam920** [kechankrisna/flutter_usb_printer#4]
testing in android, getting below error

![image](https://user-images.githubusercontent.com/20491308/145713347-2b49c4ee-4b1c-4f8d-aefd-c7314dc06ba3.png)

**Comment by Soup98** [comment]
Getting the same issue, did you manage to fix it?

**Comment by selvam920** [comment]
not yet

**Comment by selvam920** [comment]
you can use, it's tested working fine.

https://github.com/selvam920/flutter_usb_printer

**Comment by kechankrisna** [comment]
I have merged and published.
