### ISSUE TITLE
Printing Error

### ISSUE THREAD

**Issue by kaung-san-hein** [kechankrisna/flutter_usb_printer#6]
I copied code from the flutter_usb_printer example. 
Everything is fine.
When I click the _print() function, await flutterUsbPrinter.printText("Testing ESC POS printer...") function, await flutterUsbPrinter.printRawText("text") and await flutterUsbPrinter.write(data) are return true but printing is not working.

**Comment by kechankrisna** [comment]
which device you tried? android, ios or windows?

**Comment by kaung-san-hein** [comment]
android
the printer is canon.

**Comment by kechankrisna** [comment]
> android the printer is canon.

is that kind of thermal printer?

**Comment by kaung-san-hein** [comment]
No, that isn't.
The printer I used is a laser printer.

**Comment by kechankrisna** [comment]
> No, that isn't. The printer I used is a laser printer.

This package is created in order to integrate printing with thermal printer. for none thermal pos printer, I recommended you to try a packing name: [printing](https://pub.dev/packages/printing) . This package will open up native printer dialog to print every document.

**Comment by kaung-san-hein** [comment]
Ok, Thank you.
